dist: trusty
language: node_js
node_js:
  - 9
cache:
  directories:
    - node_modules
addons:
  chrome: stable
script:
  - yarn build
  - yarn test
env:
  - GOOGLE_CHROME_BINARY=/usr/bin/chromium-browser