language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
addons:
  packages:
    - google-chrome-beta
script:
  - yarn build
  - yarn test
env:
  - GOOGLE_CHROME_BINARY=/usr/bin/google-chrome-beta